package Bai10.FTPServer;


import Bai10.FTPServer.DBAccess;
import javax.swing.JOptionPane;
import javax.swing.JComponent;
import java.awt.Container;
import java.awt.Component;
import java.io.File;
import java.lang.Object;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TienDat
 */
public class frmDangKyUser extends javax.swing.JFrame {

    /**
     * Creates new form frmDangKyUser
     */
    public frmDangKyUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooserServer = new javax.swing.JFileChooser();
        txtUsename = new javax.swing.JTextField();
        txtDuongdan = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cbowrite = new javax.swing.JRadioButton();
        cbofull = new javax.swing.JRadioButton();
        cboread = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btDangky = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnTaolai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnTimduyet = new javax.swing.JButton();
        txtcpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký tài khoản");

        txtUsename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDuongdan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbowrite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbowrite.setText("Write");

        cbofull.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbofull.setText("Full");

        cboread.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboread.setText("Read");
        cboread.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Password");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Đường dẫn");

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Quyền");

        btDangky.setBackground(new java.awt.Color(153, 255, 204));
        btDangky.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btDangky.setText("Đăng ký");
        btDangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangkyActionPerformed(evt);
            }
        });

        btThoat.setBackground(new java.awt.Color(153, 255, 204));
        btThoat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Confirm password");

        btnTaolai.setBackground(new java.awt.Color(153, 255, 204));
        btnTaolai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTaolai.setText("Tạo lại");
        btnTaolai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaolaiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 255));
        jLabel6.setText("Register");

        btnTimduyet.setBackground(new java.awt.Color(255, 102, 102));
        btnTimduyet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimduyet.setText("Tìm duyệt");
        btnTimduyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimduyetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsename, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtPassword)
                    .addComponent(txtcpassword))
                .addGap(99, 99, 99)
                .addComponent(jLabel6)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbowrite, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(cbofull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDuongdan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimduyet))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btDangky)
                .addGap(94, 94, 94)
                .addComponent(btnTaolai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btThoat)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDuongdan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTimduyet))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboread)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cbowrite)))
                .addGap(18, 18, 18)
                .addComponent(cbofull)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDangky)
                    .addComponent(btThoat)
                    .addComponent(btnTaolai))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangkyActionPerformed
            // TODO add your handling code here:          
        String username=txtUsename.getText(); 
        String password=new String(txtPassword.getPassword()); 
        String cfPassword=new String(txtcpassword.getPassword());
        int quyen = 0;
        if(cboread.isSelected()) {
            quyen=0; 
        } else if (cbowrite.isSelected()) {
            quyen=1; 
        } else if(cbofull.isSelected())
            quyen=2;
        if(!password.equals(cfPassword))
        {
            JOptionPane.showMessageDialog(null, "Mật khẩu bị lỗi!");
        }else{
            try {
                //lấy đường dẫn của project hiện tại
                File directory = new File("");
                String path = txtDuongdan.getText();
                if(path.equals(""))
                {
                    //ko nhập đường dẫn sẽ tạo ra thư mục
                    path = directory.getCanonicalPath()+"\\"+txtUsename.getText();
                    (new File(path)).mkdir();
                    path = path.replace("\\", "/");
                }else{
                    path=path.replace("\\", "/");
                    System.out.print(path);
                    //Tag ra kết nối và thêm User vào CSDL
                    DBAccess acc=new DBAccess();
                    String query="insert into taikhoan (username,password,Duongdan,Quyentruyxuat) values('"+username+"','"+password+"','" + path + "',"+quyen + ")";
                    System.out.println(query);
                    if (acc.Update(query) > 0) {
                        JOptionPane.showMessageDialog(null, "Đăng ký thành công!");
                        xoa();
                    } else {//Đăng ký thất bại
                        JOptionPane.showMessageDialog(null, "Đăng ký thất bại!");
                    }                    
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.toString());
            }
        }        
    }//GEN-LAST:event_btDangkyActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btThoatActionPerformed

    private void btnTimduyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimduyetActionPerformed
        // tìm duyệt đường dẫn
        this.FileChooserServer.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(this.FileChooserServer.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            try {
                //lấy đường dẫn 
                String path = this.FileChooserServer.getSelectedFile().getCanonicalPath();
                txtDuongdan.setText(path);
                this.validate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi đường dẫn!");
            }
        }
        
    }//GEN-LAST:event_btnTimduyetActionPerformed

    private void btnTaolaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaolaiActionPerformed
        // Tạo lại
        xoa();
    }//GEN-LAST:event_btnTaolaiActionPerformed

    //tạo lại(xoá trắng)
    public void xoa(){
        txtUsename.setText("");
        txtPassword.setText("");
        txtcpassword.setText("");
        txtUsename.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangKyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangKyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangKyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangKyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangKyUser().setVisible(true);
            }
        });
    }

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooserServer;
    private javax.swing.JButton btDangky;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btnTaolai;
    private javax.swing.JButton btnTimduyet;
    private javax.swing.JRadioButton cbofull;
    private javax.swing.JRadioButton cboread;
    private javax.swing.JRadioButton cbowrite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDuongdan;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsename;
    private javax.swing.JPasswordField txtcpassword;
    // End of variables declaration//GEN-END:variables
}
